# -*- coding: utf-8 -*-
"""Change_dimension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZP5-blJr-8Z3bWeSBQtKwj_fyRjYVnY
"""

import numpy as np
import cv2 as cv
import os



# def getStart(size,req):
#     mid=size//2
#     start=mid-req//2
#     return start

# def change_dimension(img_name):
#     img=cv.imread(img_name)
#     ht,wd,cc=img.shape
#     if ht<=720 and wd<=1024:
#         top=(720-ht)//2
#         bottom=720-ht-top
#         left=(1024-wd)//2
#         right=(1024-wd-left)
#         borderType=cv.BORDER_REFLECT
#         img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
#         #img_modified = cv.GaussianBlur(img_modified,(5,5),2)
#         # cv.imshow('modified',img_modified)
#         thispath = "drive/MyDrive/Dataset_Human_Dimension/" + str(img_name)
#         print(thispath)
#         cv.imwrite(thispath, img_modified)
#     elif ht>720 and wd > 1024:
#         ht_start=getStart(ht,720)
#         wd_start=getStart(wd,1024)
#         img_modified=img[ht_start:ht_start+720,wd_start:wd_start+1024]
#         # cv.imwrite('train_input/'+img_name,img_modified)
#         # img_modified = cv.GaussianBlur(img_modified,(5,5),2)
#         cv.imwrite(f'drive/MyDrive/Dataset_Human_Dimension/{img_name}',img_modified)
#     else:
#         if ht>720:
#             print(ht)
#             ht_start=getStart(ht,720)
#             print(ht_start)
#             img=img[ht_start:ht_start+720]
#             ht=720
#             top=(720-ht)//2
#             bottom=720-ht-top
#             left=(1024-wd)//2
#             right=(1024-wd-left)
#             borderType=cv.BORDER_REFLECT
#             img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
#             cv.imwrite(f'drive/MyDrive/Dataset_Human_Dimension/{img_name}',img_modified)
#             # cv.imshow('modified',img_modified)
#             # cv.imwrite('train_input/'+img_name,img_modified)
#             # cv.imwrite('aaaaa.jpg',img_modified)
#         else:
#             wd_start=getStart(wd,1024)
#             img=img[:,wd_start:wd_start+1024]
#             wd=1024
#             top=(720-ht)//2
#             bottom=720-ht-top
#             left=(1024-wd)//2
#             right=(1024-wd-left)
#             borderType=cv.BORDER_REFLECT
#             img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
#             cv.imwrite(f'drive/MyDrive/Dataset_Human_Dimension/{img_name}',img_modified)

def getStart(size,req):
    mid=size//2
    start=mid-req//2
    return start

def change_dimension(img_name):
    img=cv.imread(img_name)
    ht,wd,cc=img.shape
    if ht<=720 and wd<=1024:
        top=(720-ht)//2
        bottom=720-ht-top
        left=(1024-wd)//2
        right=(1024-wd-left)
        borderType=cv.BORDER_REFLECT
        img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
        #img_modified = cv.GaussianBlur(img_modified,(5,5),2)
        # cv.imshow('modified',img_modified)
        cv.imwrite(f'../Dataset/{img_name}',img_modified)
    elif ht>720 and wd > 1024:
        ht_start=getStart(ht,720)
        wd_start=getStart(wd,1024)
        img_modified=img[ht_start:ht_start+720,wd_start:wd_start+1024]
        # cv.imwrite('train_input/'+img_name,img_modified)
        # img_modified = cv.GaussianBlur(img_modified,(5,5),2)
        cv.imwrite(f'../Dataset/{img_name}',img_modified)
    else:
        if ht>720:
            print(ht)
            ht_start=getStart(ht,720)
            print(ht_start)
            img=img[ht_start:ht_start+720]
            ht=720
            top=(720-ht)//2
            bottom=720-ht-top
            left=(1024-wd)//2
            right=(1024-wd-left)
            borderType=cv.BORDER_REFLECT
            img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
            cv.imwrite(f'../Dataset/{img_name}',img_modified)
            # cv.imshow('modified',img_modified)
            # cv.imwrite('train_input/'+img_name,img_modified)
            # cv.imwrite('aaaaa.jpg',img_modified)
        else:
            wd_start=getStart(wd,1024)
            img=img[:,wd_start:wd_start+1024]
            wd=1024
            top=(720-ht)//2
            bottom=720-ht-top
            left=(1024-wd)//2
            right=(1024-wd-left)
            borderType=cv.BORDER_REFLECT
            img_modified = cv.copyMakeBorder( img, top, bottom, left, right, borderType)
            cv.imwrite(f'../{img_name}',img_modified)

# print(os.getcwd())

os.chdir('drive/MyDrive')

print(os.getcwd())

os.chdir('Dataset_Human')

print(os.getcwd())

files=os.listdir()

print(len(files))

print(files[0])



print(os.getcwd())

print(files[0])



for file in files:
  if file[-4:]=='.jpg':
    print(file)
    img=cv.imread(file)
    print(img.shape)
    change_dimension(file)



print(files[0])

