# -*- coding: utf-8 -*-
"""Image_Blur.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lnk_cmtm8h62MZPE2Nf3be_w2VoB1XC6
"""



from google.colab import drive
drive.mount('/content/drive')

import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt
import numpy as np

img=cv2.imread('drive/MyDrive/Dataset_Human/1 (1).jpg')

cv2_imshow(img)

kernel=np.ones((15,15),np.float32)/225

blurred=cv2.filter2D(img,-1,kernel)

cv2_imshow(blurred)

import glob
directory="drive/MyDrive/Dataset/*.*"
flag=0
for file in glob.glob(directory):
  s1=file[22:]
  print('1')
  if file.endswith(".jpg"):
    print("2")
    img=cv2.imread(file)
    s=str(file)
    print(s)
    cv2.imwrite(f'drive/MyDrive/Dataset_Human_Sharp1/{s1}',img)
    kernel=np.ones((15,15),np.float32)/225
    blurred=cv2.filter2D(img,-1,kernel)
    cv2.imwrite(f'drive/MyDrive/Dataset_Human_Blur1/{s1}',blurred)























